// <auto-generated />
namespace IdentityTask.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class shippeddata1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(shippeddata1));
        
        string IMigrationMetadata.Id
        {
            get { return "202110181142373_shippeddata1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
